<?php

namespace BlackForest\PiwikBundle\Entity;

/**
 * PiwikEcomerceStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PiwikEcomerceStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
