<?php

namespace BlackForest\PiwikBundle\Entity;

/**
 * PiwikVisitorsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PiwikVisitorsRepository extends \Doctrine\ORM\EntityRepository
{
}
