<?php

namespace BlackForest\PiwikBundle\Entity;

/**
 * PiwikPluginRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PiwikPluginRepository extends \Doctrine\ORM\EntityRepository
{
}
