<?php

namespace BlackForest\PiwikBundle\Entity;

/**
 * PiwikReferrerTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PiwikReferrerTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
