<?php

namespace BlackForest\PiwikBundle\Entity;

/**
 * PiwikLanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PiwikLanguageRepository extends \Doctrine\ORM\EntityRepository
{
}
