<?php

namespace BlackForest\PiwikBundle\Entity;

/**
 * PiwikLocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PiwikLocationRepository extends \Doctrine\ORM\EntityRepository
{
}
