<?php

namespace BlackForest\PiwikBundle\Entity;

/**
 * PiwikDeviceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PiwikDeviceRepository extends \Doctrine\ORM\EntityRepository
{
}
