<?php

namespace BlackForest\PiwikBundle\Entity;

/**
 * PiwikVisitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PiwikVisitRepository extends \Doctrine\ORM\EntityRepository
{
}
