<?php

namespace BlackForest\PiwikBundle\Entity;

/**
 * PiwikBrowserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PiwikBrowserRepository extends \Doctrine\ORM\EntityRepository
{
}
