<?php

namespace BlackForest\PiwikBundle\Entity;

/**
 * PiwikOperatingSystemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PiwikOperatingSystemRepository extends \Doctrine\ORM\EntityRepository
{
}
