<?php

namespace BlackForest\PiwikBundle\Entity;

/**
 * PiwikSearchEngineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PiwikSearchEngineRepository extends \Doctrine\ORM\EntityRepository
{
}
