<?php

namespace BlackForest\PiwikBundle\Entity;

/**
 * PiwikVisitActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PiwikVisitActionRepository extends \Doctrine\ORM\EntityRepository
{
}
