<?php

namespace BlackForest\PiwikBundle\Entity;

/**
 * PiwikResolutionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PiwikResolutionRepository extends \Doctrine\ORM\EntityRepository
{
}
