<?php

namespace BlackForest\PiwikBundle\Entity;

/**
 * PiwikActionTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PiwikActionTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
