<?php

namespace BlackForest\PiwikBundle\Entity;

/**
 * PiwikCurrencyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PiwikCurrencyRepository extends \Doctrine\ORM\EntityRepository
{
}
