<?php

namespace BlackForest\PiwikBundle\Entity;

/**
 * PiwikVisitorTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PiwikVisitorTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
