<?php

namespace BlackForest\PiwikBundle\Entity;

/**
 * PiwikCountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PiwikCountryRepository extends \Doctrine\ORM\EntityRepository
{
}
