<?php

namespace BlackForest\PiwikBundle\Entity;

/**
 * PiwikVisitPluginRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PiwikVisitPluginRepository extends \Doctrine\ORM\EntityRepository
{
}
