<?php

namespace BlackForest\PiwikBundle\Entity;

/**
 * PiwikActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PiwikActionRepository extends \Doctrine\ORM\EntityRepository
{
}
