<?php

namespace BlackForest\PiwikBundle\Entity;

/**
 * PiwikSiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PiwikSiteRepository extends \Doctrine\ORM\EntityRepository
{
}
