BlackForest\PiwikBundle\Entity\PiwikResolution:
    type: entity
    repositoryClass: BlackForest\PiwikBundle\Entity\PiwikResolutionRepository
    table: piwik_resolution

    id:
        uuid:
            type: string
            length: 32
            generator:
                strategy: NONE

    fields:
        created:
            type: datetime
            nullable: false
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            nullable: false
            gedmo:
                timestampable:
                    on: update
        name:
            type: string
            length: 16
            nullable: false

    oneToMany:
        visit:
            targetEntity: BlackForest\PiwikBundle\Entity\PiwikVisit
            mappedBy: resolution

    manyToOne:
        site:
            targetEntity: BlackForest\PiwikBundle\Entity\PiwikSite
            inversedBy: resolution
            joinColumn:
                referencedColumnName: uuid

