BlackForest\PiwikBundle\Entity\PiwikCurrency:
    type: entity
    repositoryClass: BlackForest\PiwikBundle\Entity\PiwikCurrencyRepository
    table: piwik_currency

    id:
        uuid:
            type: string
            length: 32
            generator:
                strategy: NONE

    fields:
        created:
            type: datetime
            nullable: false
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            nullable: false
            gedmo:
                timestampable:
                    on: update
        name:
            type: string
            length: 128
            nullable: false
        symbol:
            type: string
            length: 128
            nullable: false

    oneToMany:
        visit:
            targetEntity: BlackForest\PiwikBundle\Entity\PiwikVisit
            mappedBy: currency

    manyToOne:
        site:
            targetEntity: BlackForest\PiwikBundle\Entity\PiwikSite
            inversedBy: currencies
            joinColumn:
                referencedColumnName: uuid
