BlackForest\PiwikBundle\Entity\PiwikBrowser:
    type: entity
    repositoryClass: BlackForest\PiwikBundle\Entity\PiwikBrowserRepository
    table: piwik_browser

    id:
        uuid:
            type: string
            length: 32
            generator:
                strategy: NONE

    fields:
        created:
            type: datetime
            nullable: false
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            nullable: false
            gedmo:
                timestampable:
                    on: update
        name:
            type: string
            length: 128
            nullable: false
        version:
            type: string
            length: 12
            nullable: false
        code:
            type: string
            length: 6
            nullable: false
        engine:
            type: string
            length: 64
            nullable: false
        icon:
            type: text
            nullable: true

    oneToMany:
        visit:
            targetEntity: BlackForest\PiwikBundle\Entity\PiwikVisit
            mappedBy: browser

    manyToOne:
        site:
            targetEntity: BlackForest\PiwikBundle\Entity\PiwikSite
            inversedBy: browser
            joinColumn:
                referencedColumnName: uuid
