BlackForest\PiwikBundle\Entity\PiwikLanguage:
    type: entity
    repositoryClass: BlackForest\PiwikBundle\Entity\PiwikLanguageRepository
    table: piwik_language

    id:
        uuid:
            type: string
            length: 32
            generator:
                strategy: NONE

    fields:
        created:
            type: datetime
            nullable: false
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            nullable: false
            gedmo:
                timestampable:
                    on: update
        name:
            type: string
            length: 64
            nullable: false
        code:
            type: string
            length: 8
            nullable: false

    oneToMany:
        visit:
            targetEntity: BlackForest\PiwikBundle\Entity\PiwikVisit
            mappedBy: language

    manyToOne:
        site:
            targetEntity: BlackForest\PiwikBundle\Entity\PiwikSite
            inversedBy: language
            joinColumn:
                referencedColumnName: uuid
